// packages/react-with-flow/src/app/Home/containers/NoteCreator/NoteCreator.jsx
// @flow
import classNames from 'classnames'
import notie from 'notie'
import React, { FormEvent, PureComponent } from 'react'
import { connect } from 'react-redux'
import styles from './NoteCreator.less'
import { createNoteAction } from 'src/redux/ducks/notes'

interface IState {}

const mapDispatchToProps = {
  createNote: createNoteAction,
}

type IDispatchToPropsType = typeof mapDispatchToProps

type IProps = IDispatchToPropsType

export class NoteCreator extends PureComponent<IProps, IState> {
  formRef: HTMLFormElement
  titleInput: HTMLInputElement
  valueInput: HTMLInputElement

  render () {
    return (
      <div className={classNames(styles.noteCreator, 'shadow-2')}>
        <form className="row" onSubmit={this.createNewNote} ref={((form) => this.formRef = form)}>
          <input
            type="text"
            ref={(input) => this.titleInput = input}
            name="newNoteTitle"
            placeholder="Title"
            className={classNames('col-xs-10', styles.title)}
            autoComplete="off"
          />
          <input
            type="text"
            ref={(input) => this.valueInput = input}
            name="newNoteValue"
            placeholder="Take a note..."
            className="col-xs-10"
            autoComplete="off"
          />
          <div className="actions col-xs-12 row between-xs">
            <button type="submit" className="btn-light">
              Done
            </button>
          </div>
        </form>
      </div>
    )
  }

  createNewNote = (event: FormEvent<{}>) => {
    event.preventDefault()
    if (!(this.titleInput.value && this.valueInput.value)) {
      notie.alert({
        type: 'error',
        text: 'Note Title or Content should not be empty!',
      })
      return
    }

    this.props.createNote({ title: this.titleInput.value, value: this.valueInput.value})
    this.resetForm()
  }

  resetForm = () => {
    this.formRef.reset()
  }
}

export default connect(null, mapDispatchToProps)(NoteCreator)

// packages/vue-3/src/components/NoteCreator.vue
<template>
  <div class="note-creator shadow-2">
    <form class="row" @submit="handleSubmit">
      <input
        type="text"
        name="newNoteTitle"
        placeholder="Title"
        class="col-xs-10 title"
        autoComplete="off"
        v-model="title"
      />
      <input
        type="text"
        name="newNoteValue"
        placeholder="Take a note..."
        class="col-xs-10"
        autoComplete="off"
        v-model="value"
      />
      <div class="actions col-xs-12 row between-xs">
        <button type="submit" class="btn-light">Done</button>
      </div>
    </form>
  </div>
</template>

<script>
import { defineComponent, reactive, toRefs } from "vue";
import { nanoid } from 'nanoid'

export default defineComponent({
  setup(props, ctx) {
    const noteForm = reactive({
      title: "",
      value: "",
    });

    /**
    @param {UIEvent} event
    **/
    function handleSubmit(event) {
      event.preventDefault();

      if (!noteForm.title || !noteForm.value) {
        alert("Note Title or Content should not be empty!");
        return;
      }

      ctx.emit("createNote", {
        id: nanoid(10),
        ...noteForm,
      });

      noteForm.title = "";
      noteForm.value = "";
    }

    return { ...toRefs(noteForm), handleSubmit };
  },
});
</script>

<style lang="scss" scoped>
.note-creator {
  padding: 20px;
  background-color: white;
  border-radius: 3px;
}

.title {
  font-weight: bold;
  color: rgba(0, 0, 0, 0.8);
}
</style>
