// packages/nervjs-stater-IE/src/shared/components/AppBar/AppBar.jsx
import classNames from 'classnames'
import React from 'react'

import styles from './AppBar.less'

export class AppBar extends React.PureComponent {
  render () {
    return (
      <header className={classNames(styles.appBar, 'row', 'middle-xs')}>
        <a href="/app" className={classNames(styles.logo, 'col-xs-10')}>
          Retain
        </a>
        <nav className="col-xs-2">
          <div className="row middle-xs between-xs">
            <a className={styles.link} href="/app/about">About</a>
            <span className={styles.link}>SignOut</span>
          </div>
        </nav>
      </header>
    )
  }
}

// packages/angular/src/app/shared/components/app-bar/app-bar.component.ts
import { AuthService } from './../../services/auth.service';
import { Component, OnInit } from '@angular/core';


@Component({
  selector: 'rt-app-bar',
  templateUrl: './app-bar.component.html',
  styleUrls: ['./app-bar.component.css']
})
export class AppBarComponent {
  constructor(private authService: AuthService) { }

  signOut() {
    this.authService.signOut();
  }
}

<header class="app-bar row middle-xs">
  <span [routerLink]="['']" class="logo col-xs-10">
    Retain
  </span>
<nav class="col-xs-2">
    <div class="row middle-xs between-xs">
        <span class="link" [routerLink]="['about']">About</span>
        <span class="link" (click)="signOut()">Signout</span>
    </div>
</nav>
</header>
